apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverse-proxy
  namespace: devops-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reverse-proxy
  template:
    metadata:
      labels:
        app: reverse-proxy
    spec:
      containers:
      - name: nginx
        image: <DOCKERHUB_USERNAME>/k8s-nginx:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: reverse-proxy
  namespace: devops-demo
spec:
  selector:
    app: reverse-proxy
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      # NodePort range 30000-32767; explicit is easier to remember
      nodePort: 30080
